# syntax=docker/dockerfile:1.4

##
## Go
##

# Cross compile from native platform to target arch
FROM --platform=$BUILDPLATFORM ghcr.io/linkerd/dev:v40-go as go
WORKDIR /build
COPY --link go.mod go.sum ./
COPY --link ./cni-plugin ./cni-plugin
COPY --link ./proxy-init ./proxy-init
COPY --link ./internal ./internal
RUN go mod download
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH GO111MODULE=on \
    go build -o /go/bin/linkerd-cni -mod=readonly -ldflags "-s -w" -v ./cni-plugin/

##
## Runtime dependencies
##

FROM debian:bullseye-slim as deps
WORKDIR /linkerd
RUN apt-get update && apt-get install -y --no-install-recommends \
    inotify-tools \
    procps \
    jq && \
    rm -rf /var/lib/apt/lists/*

##
## Runtime
##

FROM scratch as runtime
COPY --from=deps /usr/bin/inotifywait /usr/bin/inotifywait
COPY --from=deps /usr/bin/pgrep /usr/bin/pgrep
COPY --from=deps /usr/bin/jq /usr/bin/jq
COPY --from=go /go/bin/linkerd-cni /opt/cni/bin/
COPY LICENSE .
COPY cni-plugin/deployment/scripts/install-cni.sh .
COPY cni-plugin/deployment/linkerd-cni.conf.default .
COPY cni-plugin/deployment/scripts/filter.jq .
ENV PATH=/linkerd:/opt/cni/bin:$PATH
CMD ["install-cni.sh"]
