FROM golang:1.25.5-alpine
ENV GOCACHE=/tmp/
WORKDIR /src
COPY go.mod go.sum .
COPY proxy-init/integration/iptables/. .
RUN go mod tidy && go mod download
RUN go build -o /usr/local/bin/test_service ./test_service/test_service.go
ENTRYPOINT ["/usr/local/bin/test_service"]
