---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cni-plugin-tester-deployment
  namespace: cni-plugin-test
  labels:
    app: cni-plugin-tester
spec:
  selector:
    matchLabels:
      app: cni-plugin-tester
  replicas: 1
  template:
    metadata:
      labels:
        app: cni-plugin-tester
    spec:
      containers:
        - name: cni-plugin-tester
          image: test.l5d.io/linkerd/cni-plugin-tester:test
      initContainers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sleep
          args:
            - "infinity"
        - name: linkerd-network-validator
          image: cr.l5d.io/linkerd/proxy:edge-22.12.1
          imagePullPolicy: IfNotPresent
          securityContext:
           runAsUser: 65534
           capabilities:
              drop:
                - all
          command:
            - /usr/lib/linkerd/linkerd2-network-validator
          args:
           - --log-format
           - plain
           - --log-level
           - debug
           - --connect-addr
           - 1.1.1.1:20001
           - --listen-addr
           - 0.0.0.0:4140
           - --timeout
           - 10s
---
apiVersion: v1
kind: Service
metadata:
  name: cni-plugin-tester
  namespace: cni-plugin-test
spec:
  ports:
  - name: service
    port: 8080
  selector:
    app: cni-plugin-tester
---