# syntax=docker/dockerfile:1.4

FROM golang:1.18-alpine AS build
ENV GOCACHE=/tmp/
WORKDIR /src
COPY --link go.mod go.sum .
COPY --link cni-plugin cni-plugin
COPY --link internal internal
COPY --link proxy-init proxy-init
RUN go mod tidy && go mod download
