name: cni-plugin-installer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - cni-plugin/deployment/scripts/**

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - run: just cni-plugin-installer-integration-run
