name: cni-plugin-installer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - cni-plugin/deployment/scripts/**

jobs:
  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - uses: linkerd/dev/actions/setup-tools@v39
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76
      - uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7
      - run: just cni-plugin-installer-integration-run
