name: cni-plugin-installer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - cni-plugin/deployment/scripts/**

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: just cni-plugin-installer-integration-run
