name: Go

on:
  pull_request:
    paths:
      - .github/workflows/go.yml
      - '**/*.go'
      - go.sum
      - justfile

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    container: ghcr.io/linkerd/dev:v49-go
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
      - run: just go-lint --verbose --timeout=10m

  fmt:
    runs-on: ubuntu-24.04
    container: ghcr.io/linkerd/dev:v49-go
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
      - run: just go-fmt-check

  unit-test:
    runs-on: ubuntu-24.04
    container: ghcr.io/linkerd/dev:v49-go
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
      - run: just go-test

