name: Markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/markdown.yml

jobs:
  md-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: DavidAnson/markdownlint-cli2-action@bb4bb94c73936643d73d345b48fead3e96f90a5e
        with:
            globs: "**/*.md"
