name: Markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/markdown.yml

jobs:
  md-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: DavidAnson/markdownlint-cli2-action@455b6612a7b7a80f28be9e019b70abdd11696e4e
        with:
            globs: "**/*.md"
