name: cni-plugin release

on:
  pull_request:
    paths:
      - .github/workflows/release-cni-plugin.yml
  push:
    tags: ["cni-plugin/v*"]

permissions:
  contents: read

jobs:
  meta:
    timeout-minutes: 3
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - id: meta
        uses: ./.github/actions/version-mode
        with:
          package: cni-plugin
    outputs:
      repo: ${{ steps.meta.outputs.repo }}
      mode: ${{ steps.meta.outputs.mode }}
      version: ${{ steps.meta.outputs.version }}

  docker-publish:
    needs: meta
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    permissions:
      id-token: write # needed for signing the images with GitHub OIDC token
    steps:
      # Build multi-arch docker images for cni-plugin:
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: cni-plugin-${{ needs.meta.outputs.mode }}-${{ needs.meta.outputs.version }}
          restore-keys: cni-plugin-${{ needs.meta.outputs.mode }}-

      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
      - uses: linkerd/dev/actions/setup-tools@v49
        with:
          version: v49
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: |
          just cni-plugin-image='${{ needs.meta.outputs.repo }}:${{ needs.meta.outputs.version }}' \
                build-cni-plugin-image \
                  --cache-from type=local,src="$RUNNER_TEMP/.buildx-cache" \
                  --cache-to type=local,dest="$RUNNER_TEMP/.buildx-cache",mode=max \
                  --platform linux/amd64,linux/arm64
      - run: just-dev prune-action-cache "$RUNNER_TEMP/.buildx-cache"

      # Only publish images on release
      - if: needs.meta.outputs.mode == 'release'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_GHCR_USERNAME }}
          password: ${{ secrets.DOCKER_GHCR_PAT }}
      - if: needs.meta.outputs.mode == 'release'
        run: |
          just cni-plugin-image='${{ needs.meta.outputs.repo }}:${{ needs.meta.outputs.version }}' \
                build-cni-plugin-image \
                  --cache-from type=local,src="$RUNNER_TEMP/.buildx-cache" \
                  --cache-to type=local,dest="$RUNNER_TEMP/.buildx-cache",mode=max \
                  --platform linux/amd64,linux/arm64 \
                  --output type=registry
      - if: needs.meta.outputs.mode == 'release'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6
      - if: needs.meta.outputs.mode == 'release'
        run: cosign sign -y "${{ needs.meta.outputs.repo }}:${{ needs.meta.outputs.version }}"
        env:
          COSIGN_EXPERIMENTAL: 1

  github:
    needs: [meta, docker-publish]
    timeout-minutes: 5
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - if: needs.meta.outputs.mode == 'release'
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
        with:
          name: cni-plugin ${{ needs.meta.outputs.version }}
