name: Validator release

on:
  pull_request:
    paths:
      - .github/workflows/release-validator.yml
  push:
    tags: ["validator/v*"]

permissions:
  contents: read

jobs:
  meta:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    container: ghcr.io/linkerd/dev:v48-rust
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - uses: ./.github/actions/version-mode
        id: meta
        with:
          package: validator
          check: true
    outputs:
      repo: ${{ steps.meta.outputs.repo }}
      mode: ${{ steps.meta.outputs.mode }}
      version: ${{ steps.meta.outputs.version }}

  package:
    needs: meta
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [windows, linux]
        exclude:
          - os: windows
            arch: arm64
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    container: ghcr.io/linkerd/dev:v48-rust-musl
    steps:
      - name: Install MinGW
        if: matrix.os == 'windows'
        run: apt-get update && apt-get install mingw-w64 -y
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - run: just validator arch=${{ matrix.arch }} os=${{ matrix.os }} profile=release version=${{ needs.meta.outputs.version }} package
        env:
          CARGO: "cargo auditable"
      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.arch }}-${{ matrix.os }}-artifacts
          path: target/package/

  publish:
    needs: [meta, package]
    timeout-minutes: 5
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          path: ${{ runner.temp }}/artifacts
      - run: find "$RUNNER_TEMP"/artifacts -type f -ls
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - if: needs.meta.outputs.mode == 'release'
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe
        with:
          name: validator ${{ needs.meta.outputs.version }}
          files: ${{ runner.temp }}/artifacts/**/*
